# Generated by Django 5.1.1 on 2024-09-09 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('fathers_name', models.CharField(max_length=100)),
                ('personal_email', models.EmailField(max_length=254)),
                ('work_email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=15)),
                ('date_of_joining', models.DateField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('employment_type', models.CharField(max_length=50)),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('designation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('enable_portal_access', models.BooleanField(default=False)),
                ('aadhar_card', models.CharField(max_length=20)),
                ('pan', models.CharField(max_length=10)),
                ('residential_address', models.TextField()),
                ('pf_account_number', models.CharField(max_length=20)),
                ('annual_ctc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_holder_name', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=20)),
                ('ifsc', models.CharField(max_length=11)),
                ('account_type', models.CharField(max_length=20)),
                ('total_work_experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('dat_work_experience', models.DecimalField(decimal_places=2, max_digits=4)),
                ('skill_set', models.TextField()),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
